### ISSUE TITLE
Not compatible with PDO syntax

### ISSUE THREAD

**Issue by maximvd** [Brackets-Themes/Monokai#10]
Could you please add support for the PDO keywords

**Comment by MiguelCastillo** [comment]
@maximvd is PDO syntax supported by CodeMirror?  The way it works is that CodeMirror would add support for PDO syntax, which generates the proper style class that can be in the theme file.  I am just curious if this is the right place to fix this.

**Comment by maximvd** [comment]
Thanks for the fast respone. I'm not sure about that, I'll have a look at that first.

**Comment by maximvd** [comment]
I've contacted the developer of CodeMirror and he won't implement PDO compatibility unless I (or someone else) pay him. So I'll close this issue as it has nothing to do with your awesome theme.

**Comment by MiguelCastillo** [comment]
@maximvd Yeah I saw that. Sorry :/  Why don't you try to implement it?  I will help where I can if you have it in a public repo.

**Comment by maximvd** [comment]
So I added the keywords to the list of recognized words, do you think this will do?, as far as the theme goes it works.
https://github.com/codemirror/CodeMirror/compare/master...maximvd:patch-1

**Comment by mackenza** [comment]
What do you mean by "add support for PDO keywords"?

The reason I ask is that PDO is just a library within PHP and adds some objects, methods, and constants.  In the context of a theme, like Monokai here, how would you want to see a PDO item differently from other objects, methods and constants in your PHP code?

CodeMirror is doing its job in this case.  So for instance if I enter code like the following:

``` php
$query= $db->prepare("SELECT name FROM employees");
$query->execute();
$result = $query->fetch(PDO::FETCH_ASSOC);
```

CodeMirror (which is responsible for the editor in Brackets) assigns `cm-variable` to `fetch` (a PDO object method) and to `PDO::FETCH_ASSOC`, while also assigning the `cm-variable2` class to `$query` and `$result` as they are user-defined variables.

I see from your forked CM patch that you would want the PDO predefined constants declared as `cm-atom` but I am not sure that's what you really want.

This is not limited to just PDO as there are a ton of other PHP extensions that could be considered part of the PHP language (see http://php.net/manual/en/funcref.php) and it's not limited, as @MiguelCastillo points out above, to the Monokai theme.  It's how CM treats PHP extensions as normal PHP variables rather than recognizing them as something pseudo-built in.

I think the way you would want to approach this is writing a CM mode for the PDO extension, rather than modifying the current, generic CM PHP mode.  http://codemirror.net/doc/manual.html#modeapi

**Comment by maximvd** [comment]
Thank, I only recently switched from Sublime Text 3 to Brackets and I am used to how Sublime used to display it and in my opinion it makes it a bit more readable than just white text.
Is it worth my time trying to write a new CM mode or am I better off using the patched js file?

**Comment by mackenza** [comment]
it depends on your goal.  If you want others to see something similar to you, then writing a CM mode is the way to go.  If you are just trying to make it work for you, then hacking a local fork of CM could work.

**Comment by marcelgerber** [comment]
@maximvd It'd also be interesting to see a side-by-side comparison of the same opened in Sublime Text and Brackets. Could you take some screenshots and share them?

**Comment by maximvd** [comment]
Sure, here you go: 
![naamloos](https://cloud.githubusercontent.com/assets/7513148/6599856/69cc64be-c80c-11e4-8198-afb0d3eecbbd.png)

**Comment by MiguelCastillo** [comment]
@maximvd thanks for the screenshots.  I agree with @mackenza, the better long term solution would be to create a mode to support PDO.  Creating a mode can be rather intimidating, especially if you look at the one for PHP...  I think your best bet is play around with the PHP mode and see if you can add processing for the stuff you need.

https://github.com/codemirror/CodeMirror/blob/master/mode/php/php.js#L92

**Comment by maximvd** [comment]
Thanks for the help guys, I'll definitely look into it but right now I have a lot of work for college.

**Comment by mackenza** [comment]
interesting... the only real difference is that the PDO constants such as `PDO::PARAM_STR` are identified as something different than the methods such as `$stmt->bindParam()` which seems to indicate that Sublime Text has a different treatment for PHP constants vs. CodeMirror, not actually PDO support per se.

I played around with it for a bit and it appears that ST has more classes they can assign to language elements including, in this case, a constant.  @MiguelCastillo there seems to be a cm class called `cm-def` which appears in cm themes.  Do you think it's intended for "defined" elements (which is what a PHP constant would be)?  I guess it's moot, though, if the cm PHP mode doesn't identify constants as different from cm-variable.

@maximvd you can certainly go with a solution that suits your needs.  Be aware that when you update Brackets, you will likely need to do your changes again on the CM that comes with each new release.

What a long-term solution would be would be to contribute a PR back to CM to improve the PHP mode.  The proposed changes you have would not be the way to "fix" this for others, though.  The proper fix (that may actually get merged by the CM owner) would be to alter the regex's of the PHP mode to identify more parts of the PHP language, imo.

**Comment by maximvd** [comment]
Some more screenshots, this is the php mode script.
![naamloos](https://cloud.githubusercontent.com/assets/7513148/6614314/011f95f2-c899-11e4-9b59-99a4b8dadf6d.png)
![naamloos2](https://cloud.githubusercontent.com/assets/7513148/6614315/01210900-c899-11e4-8bec-a0faeea4af8b.png)
